baseURL = "https://jazzatlas.com/"
languageCode = "en-gb"
defaultContentLanguage = "en-gb"
title = "Jazz Atlas"
theme = "hugo-blog-awesome"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.

############################## English language ################################
[Languages.en-gb]
  languageName = "English"
  languageCode = "en-gb"
  contentDir = "content/en"
  weight = 1

  [Languages.en-gb.menu]
  [[Languages.en-gb.menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[Languages.en-gb.menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20

[Languages.en-gb.params]
  sitename = "Jazz Atlas"
  defaultColor = "dark" # set color mode: dark, light, auto
  # Setting it to 'auto' applies the color scheme based on the visitor's device color preference.If you don't specify anything, ignore this parameter, or leave it blank,
  # the default value is set to 'auto'.
  # You can take a look at layouts/index.html for more information.
  description = "Weekly live jazz music recommendations and listening guides for technologists"
  mainSections = ['posts']
  toc = false # set to false to disable table of contents 'globally'
  tocOpen = false # set to true to open table of contents by default
  goToTop = true # set to false to disable 'go to top' button
  dateFormat = "" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.
  # See https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for available date formats.
  rssFeedDescription = "summary" # available options: 1) summary 2) full

[Languages.en-gb.params.author]
  avatar = "atlas.JPG" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Jazz Atlas"
  name = "Atlas"
  description = "Weekly live jazz music recommendations and listening guides for technologists. Go out and listen to something beautiful."

# Allow to override webmanifest options
[Languages.en-gb.params.webmanifest]
  name = "Jazz Atlas" # will use "params.sitename" or "title" by default
  short_name = "Jazz Atlas" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"

[[params.socialIcons]]
name = "x"
url = "https://x.com/creatine_cycle"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"
